sudo: false
language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test:coverage
notifications:
  email:
    on_success: never
    on_failure: always